backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "videos"
    label: "Videos"
    files:
      - name: "videos"
        label: "Video Cards"
        file: "content/videos.json"
        format: "json"
        fields:
          - label: "Videos"
            name: "videos"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "YouTube Link (Unlisted)",
                  name: "url",
                  widget: "string",
                }
